.TH PORT-SCANNER 1 "2025-06-28" "version 1.0" "User Commands"
.SH NAME
port-scanner \- simple TCP port scanner
.SH SYNOPSIS
.B port-scanner
.I IPv4/IPv6_address
.I port
[\fIport\fR]...
.SH DESCRIPTION
port-scanner is a simple command-line tool to check the accessibility
of TCP ports on remote hosts.
.SH EXAMPLES
.TP
.B port-scanner 192.168.1.10 80
Check if port 80 is accessible on the host 192.168.1.10.
.TP
.B port-scanner 192.168.1.10 80 443 8080
Check if ports 80, 443, and 8080 are accessible on the host 192.168.1.10.
.SH EXIT STATUS
.TP
1
Not enough arguments provided
.TP
2
Length error
.TP
3
Memory allocation failed
.TP
4
Invalid argument passed
.TP
5
System error occurred
.TP
-1
Unexpected error
.SH AUTHOR
Artyom Fedosov
.SH LICENSE
MIT License.
.SH SEE ALSO
GitHub: \fBhttps://github.com/artyom-fedosov/port-scanner\fR
