name: CMake and CTest

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Update GCC version
      run: |
        sudo apt purge -y g++-13 gcc-13
        sudo update-alternatives --remove-all gcc || true
        sudo update-alternatives --remove-all g++ || true
        sudo apt install -y g++-14 gcc-14
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-14 10
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-14 10

    - name: Install Valgrind
      run: sudo apt install -y valgrind

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}
